
project_id = "f5e8b158-fb5d-4bee-9531-c160d97e8f5b"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
pop3_port = 54325
smtp_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
buckets = [
  { name = "employee-photos", public = true }
]

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
security_manual_linking_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
max_frequency = "1s"
secure_password_change_enabled = false
enable_anonymous_sign_ins = false

[auth.email.smtp]
host = "127.0.0.1"
port = 54326
user = "fake_mail_user"
pass = "fake_mail_password"
admin_email = "admin@email.com"
sender_name = "fake_sender"

[auth.sms]
enable_signup = true
enable_confirmations = false
template = "Your code is {{ .Code }} ."
max_frequency = "1s"

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.figma]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[functions.check-overdue-clockouts]
verify_jwt = false

[functions.send-clockout-reminder]
verify_jwt = false

[functions.email-clockout]
verify_jwt = false

[edge-runtime]
enabled = true
port = 54329
inspector_port = 54330

[analytics]
enabled = false
port = 54327
vector_port = 54328
gw_port = 54329
gw_api_port = 54330

[experimental]
orioledb_version = ""
s3_host = "env(S3_HOST)"
s3_region = "env(S3_REGION)"
s3_access_key = "env(S3_ACCESS_KEY)"
s3_secret_key = "env(S3_SECRET_KEY)"
