// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxnzisioomedannzznfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4bnppc2lvb21lZGFubnp6bmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzQzMDcsImV4cCI6MjA2NjI1MDMwN30.O7lBuISjK8pumNVQraFgjBguxkqi0Aa33pDiNlHHEew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);